# Generated by Django 4.1.5 on 2023-01-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='pomodoro.user'),
        ),
    ]
